Repository Soil-labs/eden-app-2-FrontEnd, pull requests merged in 2022-12, with the labels that each got.

#681 add tests for `SelectBox`
  packages/ui/src/elements/SelectBox/SelectBox.test.tsx
Labels: testing

#686 add hook to automatically format files with `prettier` on commit
  .husky/.gitignore
  .husky/pre-commit
  package.json
  yarn.lock
Labels: dx

#687 remove prettier eslint plugin and config
  packages/config/.eslintrc.js
  packages/config/eslint-preset.js
  packages/config/package.json
  packages/graphql/package.json
  yarn.lock
Labels: dx

#716 run only storybook package for storybook
  apps/storybook/package.json
  package.json
Labels: dx

#720 clean up jest config and testing stuff
  package.json
  packages/config/jest/jest-preset.js
  packages/config/jest/setup.ts
  packages/config/package.json
  packages/context/tsconfig.json
  packages/jest-presets/README.md
  packages/jest-presets/jest/jsdom/jest-preset.js
  packages/jest-presets/jest/jsdom/jest-setup.ts
  packages/jest-presets/package.json
  packages/ui/.swcrc
  packages/ui/jest.config.js
  packages/ui/jest.config.ts
  packages/ui/package.json
  packages/ui/tsconfig.json
  yarn.lock
Labels: dx, testing

#752 ApplyByRoleContainer Integrative Test
  packages/ui/src/containers/ApplyByRoleContainer/ApplyByRoleContainer.test.tsx
  packages/ui/utils/test-utils/createMockRouter.tsx
Labels: testing
